### ISSUE TITLE
Can't use when offline

### ISSUE THREAD

**Issue by kookster** [PRX/rack-prx_auth#7]
Because it tries to make an http request on `initialize` of the `PublicKey`, it halts starting the rails app or rake tasks when offline.  This certificate could be loaded lazily, or error out in some other manner in order to prevent this issue.

```log
> bundle exec rake --trace
** Invoke default (first_time)
** Invoke test (first_time)
** Execute test
** Invoke test:run (first_time)
** Invoke test:units (first_time)
** Invoke test:prepare (first_time)
** Execute test:prepare
** Execute test:units
rake aborted!
SocketError: getaddrinfo: nodename nor servname provided, or not known
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:879:in `initialize'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:879:in `open'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:879:in `block in connect'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:878:in `connect'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:863:in `do_start'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:852:in `start'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:583:in `start'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:478:in `get_response'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/2.1.0/net/http.rb:455:in `get'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-prx_auth-0.0.4/lib/rack/prx_auth/public_key.rb:26:in `get_certificate'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-prx_auth-0.0.4/lib/rack/prx_auth/public_key.rb:21:in `get_key'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-prx_auth-0.0.4/lib/rack/prx_auth/public_key.rb:11:in `initialize'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-prx_auth-0.0.4/lib/rack/prx_auth.rb:13:in `new'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-prx_auth-0.0.4/lib/rack/prx_auth.rb:13:in `initialize'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.10/lib/action_dispatch/middleware/stack.rb:43:in `new'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.10/lib/action_dispatch/middleware/stack.rb:43:in `build'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.10/lib/action_dispatch/middleware/stack.rb:118:in `block in build'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.10/lib/action_dispatch/middleware/stack.rb:118:in `each'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.10/lib/action_dispatch/middleware/stack.rb:118:in `inject'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/actionpack-4.1.10/lib/action_dispatch/middleware/stack.rb:118:in `build'
/Users/andrew/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/railties-4.1.10/lib/rails/engine.rb:498:in `app'
```

**Comment by chrisrhoden** [comment]
I suspect you're working with an older version of this code.

**Comment by kookster** [comment]
it was the current gem, which was not at master.
